# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 700)
        self.frame = QtWidgets.QFrame(Dialog)
        self.frame.setGeometry(QtCore.QRect(0, -10, 1121, 131))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.add = QtWidgets.QPushButton(self.frame)
        self.add.setGeometry(QtCore.QRect(150, 0, 151, 131))
        self.add.setAutoFillBackground(False)
        self.add.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/add-user.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add.setIcon(icon)
        self.add.setIconSize(QtCore.QSize(70, 70))
        self.add.setObjectName("add")
        self.list = QtWidgets.QPushButton(self.frame)
        self.list.setGeometry(QtCore.QRect(300, 0, 151, 131))
        self.list.setAutoFillBackground(False)
        self.list.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/kayit2.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.list.setIcon(icon1)
        self.list.setIconSize(QtCore.QSize(70, 70))
        self.list.setObjectName("list")
        self.start = QtWidgets.QPushButton(self.frame)
        self.start.setGeometry(QtCore.QRect(0, 0, 151, 131))
        self.start.setAutoFillBackground(False)
        self.start.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/start.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.start.setIcon(icon2)
        self.start.setIconSize(QtCore.QSize(70, 70))
        self.start.setObjectName("start")
        self.state = QtWidgets.QLabel(self.frame)
        self.state.setGeometry(QtCore.QRect(450, 0, 591, 131))
        self.state.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.state.setAutoFillBackground(False)
        self.state.setStyleSheet("background-color: rgb(78, 255, 75);\n"
"background-color: rgb(70, 255, 138);\n"
"color:rgb(255, 255, 255);\n"
"font: 75 14pt \"MS Shell Dlg 2\";")
        self.state.setAlignment(QtCore.Qt.AlignCenter)
        self.state.setObjectName("state")
        self.tableView = QtWidgets.QTableView(Dialog)
        self.tableView.setGeometry(QtCore.QRect(720, 120, 311, 651))
        self.tableView.setObjectName("tableView")
        self.videoset = QtWidgets.QLabel(Dialog)
        self.videoset.setEnabled(False)
        self.videoset.setGeometry(QtCore.QRect(0, 120, 721, 621))
        self.videoset.setText("")
        self.videoset.setPixmap(QtGui.QPixmap("assets/stop.png"))
        self.videoset.setScaledContents(True)
        self.videoset.setAlignment(QtCore.Qt.AlignCenter)
        self.videoset.setObjectName("videoset")

        self.retranslateUi(Dialog)
        self.start.clicked.connect(self.videoset.clear) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.state.setText(_translate("Dialog", "System is safe"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
